apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels: 
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: delt0p/pool-api:latest
        ports:
        - containerPort: 8080
